server:
  port: 0
grpc:
  server:
    port: 0
spring:
  application:
    name: grpc-spring-cloud-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:90001/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
