server:
  port: 8003
spring:
  application:
    name: spring-cloud-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KANLON/spring-cloud-config
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/