// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.linshen.grpc.cloud.lib;

public final class GreeterOuterClass {
  private GreeterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string param1 = 1;</code>
     */
    java.lang.String getParam1();
    /**
     * <code>string param1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getParam1Bytes();

    /**
     * <code>string param2 = 2;</code>
     */
    java.lang.String getParam2();
    /**
     * <code>string param2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getParam2Bytes();
  }
  /**
   * Protobuf type {@code HelloRequest}
   */
  public  static final class HelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HelloRequest)
      HelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloRequest() {
      param1_ = "";
      param2_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              param1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              param2_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.class, com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.Builder.class);
    }

    public static final int PARAM1_FIELD_NUMBER = 1;
    private volatile java.lang.Object param1_;
    /**
     * <code>string param1 = 1;</code>
     */
    public java.lang.String getParam1() {
      java.lang.Object ref = param1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        param1_ = s;
        return s;
      }
    }
    /**
     * <code>string param1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParam1Bytes() {
      java.lang.Object ref = param1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAM2_FIELD_NUMBER = 2;
    private volatile java.lang.Object param2_;
    /**
     * <code>string param2 = 2;</code>
     */
    public java.lang.String getParam2() {
      java.lang.Object ref = param2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        param2_ = s;
        return s;
      }
    }
    /**
     * <code>string param2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParam2Bytes() {
      java.lang.Object ref = param2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getParam1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, param1_);
      }
      if (!getParam2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, param2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getParam1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, param1_);
      }
      if (!getParam2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, param2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest)) {
        return super.equals(obj);
      }
      com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest other = (com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest) obj;

      boolean result = true;
      result = result && getParam1()
          .equals(other.getParam1());
      result = result && getParam2()
          .equals(other.getParam2());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PARAM1_FIELD_NUMBER;
      hash = (53 * hash) + getParam1().hashCode();
      hash = (37 * hash) + PARAM2_FIELD_NUMBER;
      hash = (53 * hash) + getParam2().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HelloRequest)
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.class, com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.Builder.class);
      }

      // Construct using com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        param1_ = "";

        param2_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloRequest_descriptor;
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest getDefaultInstanceForType() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest build() {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest buildPartial() {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest result = new com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest(this);
        result.param1_ = param1_;
        result.param2_ = param2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest) {
          return mergeFrom((com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest other) {
        if (other == com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest.getDefaultInstance()) return this;
        if (!other.getParam1().isEmpty()) {
          param1_ = other.param1_;
          onChanged();
        }
        if (!other.getParam2().isEmpty()) {
          param2_ = other.param2_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object param1_ = "";
      /**
       * <code>string param1 = 1;</code>
       */
      public java.lang.String getParam1() {
        java.lang.Object ref = param1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          param1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string param1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getParam1Bytes() {
        java.lang.Object ref = param1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string param1 = 1;</code>
       */
      public Builder setParam1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        param1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string param1 = 1;</code>
       */
      public Builder clearParam1() {
        
        param1_ = getDefaultInstance().getParam1();
        onChanged();
        return this;
      }
      /**
       * <code>string param1 = 1;</code>
       */
      public Builder setParam1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        param1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object param2_ = "";
      /**
       * <code>string param2 = 2;</code>
       */
      public java.lang.String getParam2() {
        java.lang.Object ref = param2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          param2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string param2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParam2Bytes() {
        java.lang.Object ref = param2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string param2 = 2;</code>
       */
      public Builder setParam2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        param2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string param2 = 2;</code>
       */
      public Builder clearParam2() {
        
        param2_ = getDefaultInstance().getParam2();
        onChanged();
        return this;
      }
      /**
       * <code>string param2 = 2;</code>
       */
      public Builder setParam2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        param2_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HelloRequest)
    }

    // @@protoc_insertion_point(class_scope:HelloRequest)
    private static final com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest();
    }

    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
      @java.lang.Override
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功，0不成功，1成功
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     * 失败时的消息信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 失败时的消息信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    java.util.List<java.lang.String>
        getDataList();
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    int getDataCount();
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    java.lang.String getData(int index);
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes(int index);
  }
  /**
   * Protobuf type {@code HelloReply}
   */
  public  static final class HelloReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HelloReply)
      HelloReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloReply.newBuilder() to construct.
    private HelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloReply() {
      code_ = 0;
      message_ = "";
      data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                data_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              data_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = data_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.class, com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *是否成功，0不成功，1成功
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 失败时的消息信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 失败时的消息信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList data_;
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDataList() {
      return data_;
    }
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    public java.lang.String getData(int index) {
      return data_.get(index);
    }
    /**
     * <pre>
     * 成功时返回的数据，可以为null
     * </pre>
     *
     * <code>repeated string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes(int index) {
      return data_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      for (int i = 0; i < data_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += computeStringSizeNoTag(data_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply)) {
        return super.equals(obj);
      }
      com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply other = (com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HelloReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HelloReply)
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.class, com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.Builder.class);
      }

      // Construct using com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.internal_static_HelloReply_descriptor;
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply getDefaultInstanceForType() {
        return com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply build() {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply buildPartial() {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply result = new com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.code_ = code_;
        result.message_ = message_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = data_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply) {
          return mergeFrom((com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply other) {
        if (other == com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       *是否成功，0不成功，1成功
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *是否成功，0不成功，1成功
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功，0不成功，1成功
       * </pre>
       *
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 失败时的消息信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 失败时的消息信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 失败时的消息信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 失败时的消息信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 失败时的消息信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = new com.google.protobuf.LazyStringArrayList(data_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDataList() {
        return data_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public java.lang.String getData(int index) {
        return data_.get(index);
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes(int index) {
        return data_.getByteString(index);
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public Builder setData(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public Builder addData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<java.lang.String> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public Builder clearData() {
        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 成功时返回的数据，可以为null
       * </pre>
       *
       * <code>repeated string data = 3;</code>
       */
      public Builder addDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HelloReply)
    }

    // @@protoc_insertion_point(class_scope:HelloReply)
    private static final com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply();
    }

    public static com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloReply>
        PARSER = new com.google.protobuf.AbstractParser<HelloReply>() {
      @java.lang.Override
      public HelloReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.linshen.grpc.cloud.lib.GreeterOuterClass.HelloReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgreeter.proto\".\n\014HelloRequest\022\016\n\006param" +
      "1\030\001 \001(\t\022\016\n\006param2\030\002 \001(\t\"9\n\nHelloReply\022\014\n" +
      "\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \003" +
      "(\t23\n\007Greeter\022(\n\010SayHello\022\r.HelloRequest" +
      "\032\013.HelloReply\"\000B\034\n\032com.linshen.grpc.clou" +
      "d.libb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Param1", "Param2", });
    internal_static_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
