version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: kanlon/get-started:part2
    deploy:
      #Run 5 instances of that image as a service called web（启动5个集群配置）, limiting each one to use, at most, 10% of a single core of CPU time (this could also be e.g. “1.5” to mean 1 and half core for each), and 50MB of RAM.
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      #Immediately restart containers if one fails. 失败就立即重启
      restart_policy:
        condition: on-failure
    #Map port 4000 on the host to web’s port 80.（端口对应，主机端口:docker端口）
    ports:
      - "4000:80"
    #Instruct web’s containers to share port 80 via a load-balanced network called webnet（docker之间共享80端口）. (Internally, the containers themselves publish to web’s port 80 at an ephemeral port.)
    networks:
      - webnet
#Define the webnet network with the default settings （默认配置webnet）(which is a load-balanced overlay network).
networks:
  webnet: