server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KANLON/spring-cloud-config
          search-paths: config-repo
          username:
          password:


