server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KANLON/practice/
          search-paths: spring-cloud/spring-cloud-config-git/config-repo
          username:
          password:


